pageinfo = [[1364043499,6443],
	[1364043499,6443],
	[1364033008,6848],
	[1364032119,6923],
	[1364032138,19723],
	[1364033011,6304],
	[1364032142,10548],
	[1363526804,2360],
	[1364033004,6196],
	[1364032121,63228],
	[1364033019,59505],
	[1364032134,9668],
	[1364032138,7038],
	[1364032115,7956],
	[1364032121,6463],
	[1364032136,28592],
	[1364040626,15873],
	[1364032130,11285],
	[1364046181,11916]];
pagedata = [ ["http://admissions.alfaisal.edu/","Welcome to Alfaisal Admissions","Alfaisal University seeks to attract academically gifted students who will achieve, succeed and also contribute .. Read More. Application to under...",""],
["http://admissions.alfaisal.edu/index.html","Welcome to Alfaisal Admissions","Alfaisal University seeks to attract academically gifted students who will achieve, succeed and also contribute .. Read More. Application to under...",""],
["http://admissions.alfaisal.edu/criteria.html","Criteria- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/howtoapply.html","Freshman- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/tution_fees.html","Tution &#38; Fees- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/costs%26aid.html","Costs &#38; Aid- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/why_alfaisal.html","Why Alfaisal-Alfaisal Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/vt/","AlFaisal University Virtual Tour","To view virtual tour properly, Flash Player 9.0.28 or later version is needed. Please download the latest version of Flash Player and install it o...",""],
["http://admissions.alfaisal.edu/academic_calendar.html","Academic Calendar - Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/freshman_criteria.html","Criteria Freshman- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/freshman.html","Freshman- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/transfer.html","Transfer- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/transfer_criteria.html","Criteria Transfer- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/gr_studies_cr.html","Criteria Graduate Studies- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/graduate_studies.html","Graduate Studies- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/scholarships.html","Scholarships- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/faq.html","FAQ&#39;s- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/mba.html","MBA- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""],
["http://admissions.alfaisal.edu/mbs.html","MBS- Alfaisal University Admissions","Criteria Criteria Freshman Criteraia Transfer Criteria Graduate Studies How to Apply Freshman Transfer Graduate Studies Costs &#38; Aid Tution Fees Sc...",""]];
